SUBMISSION_CHANNEL = "C02V3G9AZJ6"
ARCHIVE_CHANNEL = "C034HEGVCRL"
KNOWN_ITEMS = "/var/www/rspacex/reddit-slackbot/modfromslack/KNOWN_ITEMS.JSON"
POST_DIR = "/var/www/rspacex/reddit-slackbot/POST"
APPROVAL_THRESHOLD = 1
REMOVAL_THRESHOLD = -1